### ISSUE TITLE
Replace link to Gdrive with self-contained documentation

### ISSUE THREAD

**Issue by lacabra** [enigmampc/protocol#1]
On this page: https://github.com/enigmampc/protocol/blob/0d83a90f296731fc98c1da93530e2200a8a82484/docs/source/SubsystemArchitecture.rst, at the end of the `Client Encryption and Storage` there is a link to a file in Google Docs. The contents of that file should be included somewhere (else) in this documentation site, rather than being included as an external link.

Thanks

**Comment by apalepu23** [comment]
Appendix section with a subsection for cryptography has been added, and the link now goes there instead of external gdoc.
